name: check-bun-dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: read
  pull-requests: write
jobs:
  call-check-bun-dependencies:
    uses: flowscripter/.github/.github/workflows/check-bun-dependencies.yml@v1
    secrets:
      CREATE_PR_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
      NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
