name: release-bun-executable
on:
  push:
    branches: [main]
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write
jobs:
  call-release-bun-executable:
    uses: flowscripter/.github/.github/workflows/release-bun-executable.yml@v1
    with:
      executable-name: "mpeg-sdl-tool"
    secrets:
      PUSH_TO_MAIN_TOKEN: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
      NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
